apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpserver
  namespace: default
spec:
  dnsNames:
  - httpserver-mesh.51.cafe
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt-prod
  secretName: httpserver
  usages:
  - digital signature
  - key encipherment